"""Fiche récapitulative téléchargeable, générée uniquement depuis les sources."""
import html
from datetime import date

from app.generation import LANG_NAMES, build_context
from app.guards import allowed_numbers, is_supported, looks_wolof
from app.understanding import parse_json
from app.wolof import fiche_to_wolof

SYSTEM = """Tu prépares une FICHE PRATIQUE pour un citoyen sénégalais, UNIQUEMENT à partir des SOURCES.
Rédige la fiche ENTIÈREMENT en {lang}, sans aucun mot ni phrase dans une autre langue.
N'invente rien : si une information n'est pas dans les sources, mets null ou une liste vide.
Réponds UNIQUEMENT avec ce JSON :
{{
 "titre": "nom court de la démarche",
 "resume": "une phrase",
 "documents": ["document à préparer", "..."],
 "etapes": ["étape dans l'ordre", "..."],
 "lieux": ["où aller", "..."],
 "cout": "texte exact des sources ou null",
 "delai": "texte exact des sources ou null",
 "conseils": ["point important (validité, perte, cas particulier)", "..."]
}}
Au maximum 7 éléments par liste, chacun en une ligne."""

LABELS = {
    "fr": {"documents": "Documents à préparer", "etapes": "Étapes", "lieux": "Où aller",
           "cout": "Coût", "delai": "Délai", "conseils": "À savoir", "sources": "Sources officielles",
           "made": "Fiche générée par TEKTALMA AI le",
           "warn": "Les procédures peuvent évoluer : vérifiez auprès de l'administration avant de vous déplacer."},
    # ⚠️ Libellés wolof à faire relire par un locuteur
    "wo": {"documents": "Kayit yi nga war a waajal", "etapes": "Ni nga koy defe", "lieux": "Fan nga war a dem",
           "cout": "Njëg", "delai": "Diir", "conseils": "Lu war a xam", "sources": "Sources officielles",
           "made": "TEKTALMA AI moo defar fiche bii ci",
           "warn": "Démarches yi mën nañu soppiku : laajal ci administration bi balaa ngay dem."},
    "en": {"documents": "Documents to prepare", "etapes": "Steps", "lieux": "Where to go",
           "cout": "Cost", "delai": "Processing time", "conseils": "Good to know", "sources": "Official sources",
           "made": "Checklist generated by TEKTALMA AI on",
           "warn": "Procedures may change: check with the administration before going."},
}
LIST_KEYS = ("documents", "etapes", "lieux", "conseils")


def generate_checklist(llm, docs, question_fr: str, lang: str) -> dict:
    fiche = _checklist(llm, docs, question_fr, "fr" if lang == "wo" else lang)
    return fiche_to_wolof(llm, fiche) if lang == "wo" else fiche


def _checklist(llm, docs, question_fr: str, lang: str) -> dict:
    context = build_context(docs)
    raw = llm.generate(f"SOURCES :\n{context}\n\nDEMANDE : {question_fr}",
                       system=SYSTEM.format(lang=LANG_NAMES.get(lang, "français")), json_mode=True)
    data = parse_json(raw)
    allowed = allowed_numbers(context)
    def ok(x):  # garde-fous : chiffre sourcé + une seule langue
        return bool(x) and is_supported(str(x), allowed) and not looks_wolof(str(x))

    fiche = {"titre": str(data.get("titre") or ""), "resume": str(data.get("resume") or "")}
    if not ok(fiche["resume"]):
        fiche["resume"] = ""
    for key in LIST_KEYS:
        fiche[key] = [str(x) for x in (data.get(key) or []) if ok(x)][:7]
    for key in ("cout", "delai"):
        value = data.get(key)
        fiche[key] = str(value) if ok(value) else None
    return fiche


def checklist_html(fiche: dict, sources: list, lang: str) -> str:
    """Page HTML imprimable (Ctrl+P -> PDF) au format document officiel."""
    L = LABELS.get(lang, LABELS["fr"])
    e = html.escape

    def block(key, ordered=False):
        items = fiche.get(key) or []
        if not items:
            return ""
        tag = "ol" if ordered else "ul"
        lis = "".join(f"<li><span class='box'></span>{e(i)}</li>" for i in items)
        return f"<section><h2>{L[key]}</h2><{tag}>{lis}</{tag}></section>"

    facts = "".join(
        f"<div class='fact'><span>{L[k]}</span><strong>{e(fiche[k])}</strong></div>"
        for k in ("cout", "delai") if fiche.get(k))
    srcs = "".join(f"<li>{e(s['title'])} — {e(s['organisme'])}<br><a href='{e(s['url'])}'>{e(s['url'])}</a></li>"
                   for s in sources)
    return f"""<!doctype html><html lang="{lang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(fiche['titre'])} — TEKTALMA AI</title>
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@600;700&family=Manrope:wght@400;600&display=swap" rel="stylesheet">
<style>
 body{{margin:0;background:#E9E4D8;font-family:Manrope,Arial,sans-serif;color:#1B2235}}
 .page{{max-width:720px;margin:32px auto;background:#FBF8F1;padding:0 40px 32px;box-shadow:0 2px 18px rgba(20,30,60,.12)}}
 .flag{{height:8px;margin:0 -40px 28px;background:linear-gradient(90deg,#00853F 33.3%,#FDEF42 33.3% 66.6%,#E31B23 66.6%)}}
 .brand{{font-family:Sora,Arial,sans-serif;font-size:13px;color:#00853F;letter-spacing:.04em}}
 h1{{font-family:Sora,Arial,sans-serif;font-size:28px;margin:6px 0 8px;line-height:1.2}}
 .resume{{color:#4A5470;margin:0 0 20px}}
 .facts{{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:8px}}
 .fact{{border:1.5px solid #1B2235;padding:10px 14px;min-width:180px}}
 .fact span{{display:block;font-size:12px;color:#4A5470}} .fact strong{{font-size:15px}}
 h2{{font-family:Sora,Arial,sans-serif;font-size:16px;border-bottom:1.5px solid #1B2235;padding-bottom:6px;margin:26px 0 10px}}
 ul,ol{{list-style:none;padding:0;margin:0}} li{{display:flex;gap:10px;margin:8px 0;line-height:1.5}}
 .box{{flex:0 0 14px;height:14px;border:1.5px solid #1B2235;margin-top:4px}}
 .sources li{{display:block;font-size:13px;color:#4A5470}} a{{color:#00853F;word-break:break-all}}
 footer{{margin-top:28px;font-size:12px;color:#4A5470;border-top:1px dashed #9AA0B0;padding-top:12px}}
 @media print{{body{{background:#fff}} .page{{box-shadow:none;margin:0}}}}
</style></head><body><div class="page"><div class="flag"></div>
<div class="brand">TEKTALMA AI</div><h1>{e(fiche['titre'])}</h1>
<p class="resume">{e(fiche['resume'])}</p><div class="facts">{facts}</div>
{block('documents')}{block('etapes', True)}{block('lieux')}{block('conseils')}
<section class="sources"><h2>{L['sources']}</h2><ul>{srcs}</ul></section>
<footer>{L['made']} {date.today().strftime('%d/%m/%Y')}. {L['warn']}</footer>
</div></body></html>"""


# ---------------------------------------------------------------- PDF
_FONT_CANDIDATES = [  # polices avec les lettres wolof (ë, ñ, ŋ, à, ó)
    ("C:/Windows/Fonts/arial.ttf", "C:/Windows/Fonts/arialbd.ttf"),
    ("C:/Windows/Fonts/segoeui.ttf", "C:/Windows/Fonts/segoeuib.ttf"),
    ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    ("/Library/Fonts/Arial.ttf", "/Library/Fonts/Arial Bold.ttf"),
]


def _fonts():
    from pathlib import Path

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    if "TK" in pdfmetrics.getRegisteredFontNames():
        return "TK", "TK-Bold"
    for regular, bold in _FONT_CANDIDATES:
        if Path(regular).exists() and Path(bold).exists():
            pdfmetrics.registerFont(TTFont("TK", regular))
            pdfmetrics.registerFont(TTFont("TK-Bold", bold))
            return "TK", "TK-Bold"
    return "Helvetica", "Helvetica-Bold"


def checklist_pdf(fiche: dict, sources: list, lang: str) -> bytes:
    """Fiche PDF A4 au format document officiel (bande drapeau, cases à cocher, sources)."""
    import io

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    L = LABELS.get(lang, LABELS["fr"])
    regular, bold = _fonts()
    ink, muted, green = colors.HexColor("#1B2235"), colors.HexColor("#4A5470"), colors.HexColor("#00853F")
    e = html.escape

    st = {
        "brand": ParagraphStyle("brand", fontName=bold, fontSize=9, textColor=green, spaceAfter=4),
        "title": ParagraphStyle("title", fontName=bold, fontSize=20, leading=24, textColor=ink, spaceAfter=6),
        "resume": ParagraphStyle("resume", fontName=regular, fontSize=10.5, leading=15, textColor=muted, spaceAfter=10),
        "h2": ParagraphStyle("h2", fontName=bold, fontSize=12, textColor=green, spaceBefore=12, spaceAfter=6),
        "item": ParagraphStyle("item", fontName=regular, fontSize=10.5, leading=15, textColor=ink,
                               leftIndent=16, bulletIndent=0, spaceAfter=4,
                               bulletFontName=regular, bulletFontSize=11),
        "fact_label": ParagraphStyle("fl", fontName=regular, fontSize=8.5, textColor=muted),
        "fact_value": ParagraphStyle("fv", fontName=bold, fontSize=11, leading=14, textColor=ink),
        "src": ParagraphStyle("src", fontName=regular, fontSize=8.5, leading=12, textColor=muted, spaceAfter=5),
        "foot": ParagraphStyle("foot", fontName=regular, fontSize=8, leading=11, textColor=muted, spaceBefore=14),
    }

    story = [Paragraph("TEKTALMA AI", st["brand"]),
             Paragraph(e(fiche.get("titre", "")), st["title"])]
    if fiche.get("resume"):
        story.append(Paragraph(e(fiche["resume"]), st["resume"]))

    facts = [[Paragraph(L[k], st["fact_label"]), Paragraph(e(fiche[k]), st["fact_value"])]
             for k in ("cout", "delai") if fiche.get(k)]
    if facts:
        cells = [[Table([[f[0]], [f[1]]], colWidths=[78 * mm]) for f in facts]]
        box = Table(cells, colWidths=[82 * mm] * len(facts), hAlign="LEFT")
        box.setStyle(TableStyle([("BOX", (i, 0), (i, 0), 1.2, ink) for i in range(len(facts))]
                                + [("VALIGN", (0, 0), (-1, -1), "TOP"),
                                   ("LEFTPADDING", (0, 0), (-1, -1), 6)]))
        story += [box, Spacer(1, 4)]

    def section(key, numbered=False):
        items = fiche.get(key) or []
        if not items:
            return
        story.append(Paragraph(L[key], st["h2"]))
        for n, item in enumerate(items, start=1):
            bullet = f"{n}." if numbered else "\u25a1"
            story.append(Paragraph(e(item), st["item"], bulletText=bullet))

    section("documents")
    section("etapes", numbered=True)
    section("lieux")
    section("conseils")

    if sources:
        story.append(Paragraph(L["sources"], st["h2"]))
        for s in sources:
            story.append(Paragraph(
                f"{e(s['title'])} — {e(s['organisme'])}<br/>"
                f"<link href='{e(s['url'])}' color='#00853F'>{e(s['url'])}</link>", st["src"]))
    story.append(Paragraph(f"{L['made']} {date.today().strftime('%d/%m/%Y')}. {L['warn']}", st["foot"]))

    def page_deco(canvas, doc):  # bande aux couleurs du drapeau
        w, h = A4
        for i, c in enumerate(("#00853F", "#FDEF42", "#E31B23")):
            canvas.setFillColor(colors.HexColor(c))
            canvas.rect(i * w / 3, h - 7 * mm, w / 3 + 1, 7 * mm, stroke=0, fill=1)

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                      topMargin=18 * mm, bottomMargin=16 * mm,
                      title=fiche.get("titre", "TEKTALMA AI"), author="TEKTALMA AI").build(
        story, onFirstPage=page_deco, onLaterPages=page_deco)
    return buf.getvalue()
